/**
 * Place names, so the State and City filters hold what their labels promise.
 *
 * Sheets maintained by several people do not keep the two apart. A block may have a City
 * column and no State at all; another writes "CHENNAI" under State; a third puts
 * "Mumbai, Maharashtra" in one cell. Filed as-is, the State filter fills with cities and
 * the City filter with states, and neither is usable.
 *
 * Everything here is a lookup of a fixed, public fact — Chennai is in Tamil Nadu — not a
 * guess about a creator. A state is only ever *derived* when the sheet gave none; a state
 * the sheet states is never overruled.
 */

/** Comparison key: case, spacing and punctuation all vary, none of them meaningfully. */
function key(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, "");
}

export const STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  // Union territories.
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

/** Abbreviations, former names and common misspellings. */
const STATE_ALIASES: Record<string, string> = {
  ap: "Andhra Pradesh",
  ar: "Arunachal Pradesh",
  as: "Assam",
  br: "Bihar",
  cg: "Chhattisgarh",
  chattisgarh: "Chhattisgarh",
  ga: "Goa",
  gj: "Gujarat",
  hr: "Haryana",
  hp: "Himachal Pradesh",
  jh: "Jharkhand",
  ka: "Karnataka",
  kar: "Karnataka",
  kl: "Kerala",
  mp: "Madhya Pradesh",
  mh: "Maharashtra",
  ml: "Meghalaya",
  mn: "Manipur",
  mz: "Mizoram",
  nl: "Nagaland",
  od: "Odisha",
  or: "Odisha",
  orissa: "Odisha",
  pb: "Punjab",
  rj: "Rajasthan",
  sk: "Sikkim",
  tn: "Tamil Nadu",
  tamilnad: "Tamil Nadu",
  ts: "Telangana",
  tg: "Telangana",
  tr: "Tripura",
  up: "Uttar Pradesh",
  uk: "Uttarakhand",
  ua: "Uttarakhand",
  uttaranchal: "Uttarakhand",
  wb: "West Bengal",
  bengal: "West Bengal",
  dl: "Delhi",
  ncr: "Delhi",
  newdelhi: "Delhi",
  delhincr: "Delhi",
  jk: "Jammu and Kashmir",
  jammukashmir: "Jammu and Kashmir",
  ld: "Ladakh",
  ch: "Chandigarh",
  py: "Puducherry",
  pondicherry: "Puducherry",
  puduchery: "Puducherry",
  andaman: "Andaman and Nicobar Islands",
  andamannicobar: "Andaman and Nicobar Islands",
  damananddiu: "Dadra and Nagar Haveli and Daman and Diu",
  dadranagarhaveli: "Dadra and Nagar Haveli and Daman and Diu",
};

const STATE_BY_KEY = new Map<string, string>([
  ...STATES.map((state) => [key(state), state] as const),
  ...Object.entries(STATE_ALIASES).map(([alias, state]) => [key(alias), state] as const),
]);

/**
 * Cities whose official name changed, so a sheet using either spelling lands on one entry
 * in the filter instead of two halves of the same city.
 */
const CITY_RENAMES: Record<string, string> = {
  bangalore: "Bengaluru",
  bengaluru: "Bengaluru",
  bombay: "Mumbai",
  calcutta: "Kolkata",
  madras: "Chennai",
  poona: "Pune",
  baroda: "Vadodara",
  mysore: "Mysuru",
  mangalore: "Mangaluru",
  hubli: "Hubballi",
  belgaum: "Belagavi",
  gulbarga: "Kalaburagi",
  bellary: "Ballari",
  shimoga: "Shivamogga",
  tumkur: "Tumakuru",
  trichy: "Tiruchirappalli",
  tiruchi: "Tiruchirappalli",
  tuticorin: "Thoothukudi",
  calicut: "Kozhikode",
  cochin: "Kochi",
  ernakulam: "Kochi",
  trivandrum: "Thiruvananthapuram",
  alleppey: "Alappuzha",
  allahabad: "Prayagraj",
  gurgaon: "Gurugram",
  vizag: "Visakhapatnam",
  waltair: "Visakhapatnam",
  pondicherry: "Puducherry",
  panjim: "Panaji",
  simla: "Shimla",
};

/**
 * Major cities and their state.
 *
 * Names shared by cities in two states — Aurangabad, Bilaspur, Hamirpur, Pratapgarh,
 * Bijapur, Rampur, Balrampur — are deliberately absent. Picking one would file half the
 * creators under the wrong state, which is worse than leaving the state blank.
 */
const CITIES: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Tirupati",
    "Kadapa",
    "Anantapur",
    "Kakinada",
    "Eluru",
    "Ongole",
    "Chittoor",
    "Vizianagaram",
    "Amaravati",
  ],
  "Arunachal Pradesh": ["Itanagar", "Tawang"],
  Assam: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Tezpur", "Nagaon", "Tinsukia"],
  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chapra",
    "Sasaram",
    "Motihari",
    "Bettiah",
    "Nalanda",
  ],
  Chhattisgarh: ["Raipur", "Bhilai", "Korba", "Durg", "Raigarh", "Jagdalpur", "Ambikapur"],
  Goa: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Calangute", "Ponda"],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Gandhinagar",
    "Junagadh",
    "Anand",
    "Bharuch",
    "Nadiad",
    "Mehsana",
    "Navsari",
    "Vapi",
    "Morbi",
    "Bhuj",
  ],
  Haryana: [
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
    "Bhiwani",
    "Kurukshetra",
  ],
  "Himachal Pradesh": ["Shimla", "Manali", "Dharamshala", "Solan", "Mandi", "Kullu", "Kasauli"],
  Jharkhand: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Hazaribagh", "Giridih"],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Hubballi",
    "Mangaluru",
    "Belagavi",
    "Kalaburagi",
    "Davanagere",
    "Ballari",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Hassan",
    "Dharwad",
    "Chikmagalur",
    "Coorg",
    "Madikeri",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Alappuzha",
    "Kannur",
    "Palakkad",
    "Malappuram",
    "Kottayam",
    "Munnar",
    "Wayanad",
    "Pathanamthitta",
    "Idukki",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Khandwa",
    "Chhindwara",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Thane",
    "Solapur",
    "Navi Mumbai",
    "Kolhapur",
    "Amravati",
    "Nanded",
    "Sangli",
    "Jalgaon",
    "Akola",
    "Latur",
    "Ahmednagar",
    "Chandrapur",
    "Parbhani",
    "Satara",
    "Ratnagiri",
    "Beed",
    "Dombivli",
    "Kalyan",
    "Vasai",
    "Virar",
    "Lonavala",
  ],
  Manipur: ["Imphal"],
  Meghalaya: ["Shillong", "Tura", "Cherrapunji"],
  Mizoram: ["Aizawl"],
  Nagaland: ["Kohima", "Dimapur"],
  Odisha: ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore"],
  Punjab: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Pathankot",
    "Hoshiarpur",
    "Moga",
    "Firozpur",
  ],
  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Udaipur",
    "Kota",
    "Ajmer",
    "Bikaner",
    "Bhilwara",
    "Alwar",
    "Sikar",
    "Pali",
    "Jaisalmer",
    "Mount Abu",
    "Pushkar",
    "Nagaur",
  ],
  Sikkim: ["Gangtok", "Pelling"],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Thanjavur",
    "Dindigul",
    "Nagercoil",
    "Kanchipuram",
    "Cuddalore",
    "Karur",
    "Namakkal",
    "Sivakasi",
    "Ooty",
    "Kodaikanal",
    "Hosur",
    "Tiruvannamalai",
  ],
  Telangana: [
    "Hyderabad",
    "Secunderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Ramagundam",
  ],
  Tripura: ["Agartala"],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Varanasi",
    "Meerut",
    "Prayagraj",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Noida",
    "Greater Noida",
    "Firozabad",
    "Jhansi",
    "Mathura",
    "Ayodhya",
    "Muzaffarnagar",
    "Etawah",
    "Banda",
    "Sultanpur",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Rishikesh",
    "Haldwani",
    "Roorkee",
    "Nainital",
    "Mussoorie",
    "Rudrapur",
    "Almora",
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Darjeeling",
    "Bardhaman",
    "Malda",
    "Kharagpur",
    "Kalimpong",
  ],
  Delhi: ["Delhi", "New Delhi", "Dwarka", "Rohini", "Saket"],
  Chandigarh: ["Chandigarh"],
  "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Gulmarg", "Pahalgam"],
  Ladakh: ["Leh", "Kargil"],
  Puducherry: ["Puducherry", "Karaikal", "Yanam", "Mahe"],
  "Andaman and Nicobar Islands": ["Port Blair"],
};

const CITY_STATE = new Map<string, string>();
const CITY_LABEL = new Map<string, string>();

for (const [state, cities] of Object.entries(CITIES)) {
  for (const city of cities) {
    CITY_STATE.set(key(city), state);
    CITY_LABEL.set(key(city), city);
  }
}

for (const [alias, canonical] of Object.entries(CITY_RENAMES)) {
  CITY_LABEL.set(key(alias), canonical);
  const state = CITY_STATE.get(key(canonical));
  if (state) CITY_STATE.set(key(alias), state);
}

/** The canonical state name for a value, or null when it names no state we know. */
export function canonicalState(value: string): string | null {
  return STATE_BY_KEY.get(key(value)) ?? null;
}

/** The state a city sits in, or null when the city is unknown or shared between states. */
export function stateForCity(value: string): string | null {
  return CITY_STATE.get(key(value)) ?? null;
}

/** The city's current official name, for values we recognise. */
export function canonicalCity(value: string): string | null {
  return CITY_LABEL.get(key(value)) ?? null;
}
